language : android
jdk : oraclejdk9
sudo : required

before_cache:
  -rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  -rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  -$HOME/.gradle/caches/
  -$HOME/.gradle/wrapper/

  env:
  global:
    - ANDROID_API = 24
    - EMULATOR_API = 22
    - ANDROID_BUILD_TOOLS = 24.0.2
    - ADB_INSTALL_TIMEOUT = 5 # minutos
    -
android :
  components :
  - platform-tools
  - tools
  - build-tools-24.0.2
  - android-22
  - android-24
  - sys-img-armeabi-v7a-android-22
  - extra-android-m2repository
  - addon-google_apis-google- 19

before_install:
- chmod +x gradlew

script:
  - "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"


