language : android
jdk : oraclejdk8
sudo : falso



android :
  components :
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-22
    - android-24
    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository


before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-28"

before_script:
      - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
      - emulator -avd test -no-skin -no-audio -no-window &
      - android-wait-for-emulator
      - adb shell input keyevent 82 &

script: ./gradlew connectedAndroidTest

