language : android
jdk : oraclejdk8
sudo : falso

android :
  components :
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-22
    - android-24
    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository


before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-28"

script: ./gradlew connectedAndroidTest