language : android
jdk : oraclejdk8
sudo : falso

android :
  components :
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-22
    - android-24
    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository
    - licenses:
        - 'android-sdk-preview-license-52d11cd2'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'

before_install:
  - chmod +x gradlew

script: ./gradlew connectedAndroidTest